-- Shared kanji radical metadata for study cards and teacher upkeep.

create table if not exists public.kanji_radicals (
  kanji text primary key,
  radical text not null,
  radical_name text,
  stroke_count integer,
  notes text,
  source text not null default 'mekuru_teacher',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  constraint kanji_radicals_single_kanji check (char_length(kanji) = 1),
  constraint kanji_radicals_single_radical check (char_length(radical) = 1),
  constraint kanji_radicals_stroke_count_positive check (stroke_count is null or stroke_count > 0)
);

comment on table public.kanji_radicals is
  'Shared radical/stroke metadata for kanji study cards.';

comment on column public.kanji_radicals.radical_name is
  'Short English display name for the radical, for example speech, water, hand.';

alter table public.kanji_radicals enable row level security;

drop policy if exists "kanji_radicals_select_authenticated" on public.kanji_radicals;
create policy "kanji_radicals_select_authenticated"
on public.kanji_radicals
for select
to authenticated
using (true);

drop policy if exists "kanji_radicals_manage_super_teachers" on public.kanji_radicals;
create policy "kanji_radicals_manage_super_teachers"
on public.kanji_radicals
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and (p.role = 'super_teacher' or coalesce(p.is_super_teacher, false) = true)
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and (p.role = 'super_teacher' or coalesce(p.is_super_teacher, false) = true)
  )
);

create index if not exists kanji_radicals_radical_idx on public.kanji_radicals(radical);

create table if not exists public.kanji_components (
  id bigint generated by default as identity primary key,
  kanji text not null references public.kanji_radicals(kanji) on delete cascade,
  component text not null,
  component_name text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  constraint kanji_components_single_kanji check (char_length(kanji) = 1),
  constraint kanji_components_single_component check (char_length(component) = 1),
  constraint kanji_components_unique_component unique (kanji, component)
);

alter table public.kanji_components enable row level security;

drop policy if exists "kanji_components_select_authenticated" on public.kanji_components;
create policy "kanji_components_select_authenticated"
on public.kanji_components
for select
to authenticated
using (true);

drop policy if exists "kanji_components_manage_super_teachers" on public.kanji_components;
create policy "kanji_components_manage_super_teachers"
on public.kanji_components
for all
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and (p.role = 'super_teacher' or coalesce(p.is_super_teacher, false) = true)
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and (p.role = 'super_teacher' or coalesce(p.is_super_teacher, false) = true)
  )
);

create index if not exists kanji_components_kanji_idx on public.kanji_components(kanji, sort_order);
